###
GET http://localhost:3001/api/comments
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY4OWIyMjA2YmEzNDFlMzI4ZWQ2NDUiLCJmaXJzdE5hbWUiOiJSYWtlc2giLCJsYXN0TmFtZSI6Ik5hbGFib3RodSIsImhhbmRsZSI6InJha2hpIiwiZW1haWwiOiJyYWtlc2huMUBuLmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8yLmpwZyIsImlkIjo0LCJpYXQiOjE2NTEwMjM1NDB9.O6FTTXxjSp4107THGMRSGAE17-LKA-Y5IhbBi3J8CO8

###
GET http://localhost:3001/api/comments/task/62697922f627e75a60fec2d3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY4OWIyMjA2YmEzNDFlMzI4ZWQ2NDUiLCJmaXJzdE5hbWUiOiJSYWtlc2giLCJsYXN0TmFtZSI6Ik5hbGFib3RodSIsImhhbmRsZSI6InJha2hpIiwiZW1haWwiOiJyYWtlc2huMUBuLmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8yLmpwZyIsImlkIjo0LCJpYXQiOjE2NTEwMjM1NDB9.O6FTTXxjSp4107THGMRSGAE17-LKA-Y5IhbBi3J8CO8

###
GET http://localhost:3001/api/comments/comment/62705e735342de58c18a139e
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY4OWIyMjA2YmEzNDFlMzI4ZWQ2NDUiLCJmaXJzdE5hbWUiOiJSYWtlc2giLCJsYXN0TmFtZSI6Ik5hbGFib3RodSIsImhhbmRsZSI6InJha2hpIiwiZW1haWwiOiJyYWtlc2huMUBuLmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8yLmpwZyIsImlkIjo0LCJpYXQiOjE2NTEwMjM1NDB9.O6FTTXxjSp4107THGMRSGAE17-LKA-Y5IhbBi3J8CO8

###
POST http://localhost:3001/api/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY4OWIyMjA2YmEzNDFlMzI4ZWQ2NDUiLCJmaXJzdE5hbWUiOiJSYWtlc2giLCJsYXN0TmFtZSI6Ik5hbGFib3RodSIsImhhbmRsZSI6InJha2hpIiwiZW1haWwiOiJyYWtlc2huMUBuLmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8yLmpwZyIsImlkIjo0LCJpYXQiOjE2NTEwMjM1NDB9.O6FTTXxjSp4107THGMRSGAE17-LKA-Y5IhbBi3J8CO8

{
    "text": "Inserted from HTTP",
    "taskId": "62697109202f843e6034abfc",
    "isReply": true
}