http://localhost:3000

###
GET http://localhost:3000/api/users/

###
GET http://localhost:3000/api/users/1

###

DELETE  http://localhost:3000/api/users/1

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "firstName": "Rakesh",
  "lastName": "Nalabothu",
  "handle": "rakhi",
  "password": "secret",
  "email": "rakeshn1@n.edu",
  "pic": "https://randomuser.me/api/portraits/men/2.jpg"
}

###
PATCH http://localhost:3000/api/users/2
Content-Type: application/json

{
  "lastName": "Sunny"
}