es (14 sloc)  334 Bytes
   
http://localhost:3001

###
GET http://localhost:3001/api/tasks
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY4OWIyMjA2YmEzNDFlMzI4ZWQ2NDUiLCJmaXJzdE5hbWUiOiJSYWtlc2giLCJsYXN0TmFtZSI6Ik5hbGFib3RodSIsImhhbmRsZSI6InJha2hpIiwiZW1haWwiOiJyYWtlc2huMUBuLmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8yLmpwZyIsImlkIjo0LCJpYXQiOjE2NTEwMjM1NDB9.O6FTTXxjSp4107THGMRSGAE17-LKA-Y5IhbBi3J8CO8

###
GET http://localhost:3001/api/tasks/task/62697109202f843e6034abfc
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY4OWIyMjA2YmEzNDFlMzI4ZWQ2NDUiLCJmaXJzdE5hbWUiOiJSYWtlc2giLCJsYXN0TmFtZSI6Ik5hbGFib3RodSIsImhhbmRsZSI6InJha2hpIiwiZW1haWwiOiJyYWtlc2huMUBuLmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8yLmpwZyIsImlkIjo0LCJpYXQiOjE2NTEwMjM1NDB9.O6FTTXxjSp4107THGMRSGAE17-LKA-Y5IhbBi3J8CO8

###
GET http://localhost:3001/api/tasks/assignedtasks
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY4OWIyMjA2YmEzNDFlMzI4ZWQ2NDUiLCJmaXJzdE5hbWUiOiJSYWtlc2giLCJsYXN0TmFtZSI6Ik5hbGFib3RodSIsImhhbmRsZSI6InJha2hpIiwiZW1haWwiOiJyYWtlc2huMUBuLmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8yLmpwZyIsImlkIjo0LCJpYXQiOjE2NTEwMjM1NDB9.O6FTTXxjSp4107THGMRSGAE17-LKA-Y5IhbBi3J8CO8

###
GET http://localhost:3001/api/tasks/createdtasks
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY4OWIyMjA2YmEzNDFlMzI4ZWQ2NDUiLCJmaXJzdE5hbWUiOiJSYWtlc2giLCJsYXN0TmFtZSI6Ik5hbGFib3RodSIsImhhbmRsZSI6InJha2hpIiwiZW1haWwiOiJyYWtlc2huMUBuLmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8yLmpwZyIsImlkIjo0LCJpYXQiOjE2NTEwMjM1NDB9.O6FTTXxjSp4107THGMRSGAE17-LKA-Y5IhbBi3J8CO8

###
GET http://localhost:3001/api/tasks/handle/rakhi

###
DELETE http://localhost:3001/api/tasks/625878b0e6935ef1cba8451b
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY4OWIyMjA2YmEzNDFlMzI4ZWQ2NDUiLCJmaXJzdE5hbWUiOiJSYWtlc2giLCJsYXN0TmFtZSI6Ik5hbGFib3RodSIsImhhbmRsZSI6InJha2hpIiwiZW1haWwiOiJyYWtlc2huMUBuLmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8yLmpwZyIsImlkIjo0LCJpYXQiOjE2NTEwMjM1NDB9.O6FTTXxjSp4107THGMRSGAE17-LKA-Y5IhbBi3J8CO8

###
POST http://localhost:3001/api/tasks
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY4OWIyMjA2YmEzNDFlMzI4ZWQ2NDUiLCJmaXJzdE5hbWUiOiJSYWtlc2giLCJsYXN0TmFtZSI6Ik5hbGFib3RodSIsImhhbmRsZSI6InJha2hpIiwiZW1haWwiOiJyYWtlc2huMUBuLmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8yLmpwZyIsImlkIjo0LCJpYXQiOjE2NTEwMjM1NDB9.O6FTTXxjSp4107THGMRSGAE17-LKA-Y5IhbBi3J8CO8

{
  "isCompleted": false,
  "title": "Make Bulma great again",
  "dueDate": "2021-07-05T04:00:00.000Z"
}

###
PATCH   http://localhost:3001/api/tasks/62697109202f843e6034abfc
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjY4OWIyMjA2YmEzNDFlMzI4ZWQ2NDUiLCJmaXJzdE5hbWUiOiJSYWtlc2giLCJsYXN0TmFtZSI6Ik5hbGFib3RodSIsImhhbmRsZSI6InJha2hpIiwiZW1haWwiOiJyYWtlc2huMUBuLmVkdSIsInBpYyI6Imh0dHBzOi8vcmFuZG9tdXNlci5tZS9hcGkvcG9ydHJhaXRzL21lbi8yLmpwZyIsImlkIjo0LCJpYXQiOjE2NTEwMjM1NDB9.O6FTTXxjSp4107THGMRSGAE17-LKA-Y5IhbBi3J8CO8

{
  "assignedTo":"62689b2206ba341e328ed645",
  "dueDate":"2021-07-05",
  "isCompleted":false,
  "title":"Make Bulmaagain 3"
}

###
POST http://localhost:3001/api/tasks/login
Content-Type: application/json

{
  "email": "rakeshn1@n.edu",
  "password": "secret"
}

###
POST http://localhost:3001/api/tasks/seed